version: '3'
services: 
    angular:
        container_name: angular
        build: ./RestApi/nodefile
        ports: 
            - 4200:4200;
    node:
        container_name: node
        build: RestApi/angularfile
        ports:
            - 8080
    mysql: 
        container_name: mysql
        image: mysql
        ports: 
            - 27017:27017
